### ISSUE TITLE
Add support for HuggingChat custom integration 

### ISSUE THREAD

**Issue by MrAvana** [valentinfrlch/ha-gpt4vision#7]
Can you add support for HuggingChat conversation?
https://github.com/PhoenixR49/hass-huggingchat-conversation

**Comment by valentinfrlch** [comment]
I am not sure I understand.
The repo you linked is an integration that uses HuggingChat. There doesn't seem to be an official HuggingChat API.
More importantly however, huggingchat itself is essentially a user interface to interact with models. It is not meant to serve as a free provider of GPU power...

I am not sure what you mean by "support for HuggingChat conversation" because the integration you linked to is not a provider.
